### ISSUE TITLE
Check for broken links

### ISSUE THREAD

**Issue by pintergreg** [pintergreg/software-engineering#39]

**Comment by pintergreg** [comment]
possible config, expecting the the CI script donwloads and extracts the binary as in the case of mdbook itself
```toml
[output.linkcheck]
command = "./mdbook-linkcheck"
# Should we check links on the internet? Enabling this option adds a
# non-negligible performance impact
follow-web-links = true

# Are we allowed to link to files outside of the book's root directory? This
# may help prevent linking to sensitive files (e.g. "../../../../etc/shadow")
traverse-parent-directories = false

# If necessary, you can exclude one or more links from being checked with a
# list of regular expressions. The regex will be applied to the link href (i.e.
# the `./index.html` in `[some page](./index.html)`) so it can be used to
# ignore both web and filesystem links.
#
# Hint: you can use TOML's raw strings (single quote) to avoid needing to
# escape things twice.
exclude = [ 'google\.com' ]

# The User-Agent to use when sending web requests
user-agent = "mdbook-linkcheck-0.4.0"

cache-timeout = 604800 # seconds; week

# How should warnings be treated?
#
# - "warn" will emit warning messages
# - "error" treats all warnings as errors, failing the linkcheck
# - "ignore" will ignore warnings, suppressing diagnostic messages and allowing
#   the linkcheck to continuing
warning-policy = "warn"
```

```
wget -qO mdbook-linkcheck.zip https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.7/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip
unzip mdbook-linkcheck.zip
chmod +x mdbook-linkcheck
```

### issues

- only the CI script copies the presentations to the book folder, so every link from HOME.md appears as an issue
